image: alpine:latest

services:
  - postgres:13-alpine
  - gradle:6.6-alpine
  - java:8-alpine

stages:
  - build

before_script:

Building:
  stage: build
  tags: ["docker"]
  script:
    - gradle build
