stages:
  - pre-build
  - build
  - deploy

include:
  - templates/build_template.yml
  - templates/deploy_template.yml

Pre-build:
  stage: pre-build
  tags:
    - docker
  services:
    - docker:19.03.12-dind
  image: docker
  script:
    - docker build `
     `-t $DOCKER_USER/image_for_build_back:latest `
     `-f ./Dockerfile.pre-build `
     `--build-arg ALPINE_VERSION=$ALPINE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/image_for_build_back:latest
  rules:
    - if: '$RUN_REBUILD_IMAGE_FOR_BUILD != "no"'
      when: always
    - when: never

Build_dev:
  environment:
    name: dev
    deployment_tier: development
    url: http://dev-school-app.$NAMESPACE.school.telekom.sh/dev-ops-school/index.html
  tags:
    - aws_dev_deploy
  <<: *build_template

Build_prod:
  environment:
    name: prod
    deployment_tier: development
    url: http://dev-school-app.$NAMESPACE.school.telekom.sh/dev-ops-school/index.html
  tags:
    - aws_dev_deploy
  <<: *build_template

Deploy_dev:
  needs:
    - Build_dev
  environment: dev
  tags:
    - aws_dev_deploy
  <<: *deploy_teamplate

Deploy_prod:
  needs:
    - Build_prod
    - Deploy_dev
  environment: prod
  tags:
    - aws_prod_deploy
  when: manual
  <<: *deploy_teamplate
