image: alpine:latest

services:
  - postgres:13-alpine
  - java:8

stages:
  - build

before_script:
  - apk add gradle
  - gradle version


Building:
  stage: build
  tags: ["docker"]
  script:
    - gradle build
    - ls
    - java -jar \dev-school-app\build\libs\dev-school-app-1.0-SNAPSHOT.jar
