stages:
  - build

.build_temaplte: &build_template
  stage: build
  tags:
    - docker
  services:
    - docker:19.03.12-dind
  image: docker
  script:
    - sed -i "s/NAMESPACE/rvv-test/g" ./src/main/resources/application.yaml
    - sed -i "s/DB_CHART/db/g" ./src/main/resources/application.yaml
    - sed -i "s/DB_NAME/bd-test/g" ./src/main/resources/application.yaml
    - sed -i "s/DB_USER/user/g" ./src/main/resources/application.yaml
    - sed -i "s/DB_PASS/pass/g" ./src/main/resources/application.yaml
    - docker build `
     `-t $DOCKER_REGISTRY/backend:test `
     `--build-arg GRADLE_VERSION=$GRADLE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_REGISTRY/backend:test

Build_dev:
  environment:
    name: dev
    deployment_tier: development
    url: http://dev-school-app.$NAMESPACE.school.telekom.sh/dev-ops-school/index.html
  tags:
    - aws_dev_deploy
  <<: *build_template

