image: alpine:latest

stages:
  - build

before_script:
  - apk add java
  - apk add gradle
  - gradle version
  - java version

Building:
  stage: build
  tags: ["docker"]
  script:
    - gradlew build
