server:
  port: 8080

service:
  api:
    version: 1.0.0

spring:
  application:
    name: DevSchool-Application-2
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://dev_db-postgresql.rvv-dev.svc.cluster.local/db_devops_school}
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:user_dev}
    password: ${DATASOURCE_PASSWORD:pass_dev}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false


base:
  path: ${BASE_PATH:0.0.0.0:8080}
